apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freepbx-data
  namespace: asterisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
